### ISSUE TITLE
Dotnet Core 2.0

### ISSUE THREAD

**Issue by Dave3of5** [jusbuc2k/Justin.AspNetCore.LdapAuthentication#3]
Getting an Error with asp dotnet core 2.0:

> Exception has occurred: CLR/System.TypeLoadException
> An unhandled exception of type 'System.TypeLoadException' occurred in System.Private.CoreLib.dll: 'Could not load type 'Microsoft.AspNetCore.Identity.UserManager`1' from assembly 'Microsoft.AspNetCore.Identity, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'
>    at WebApplication1.Startup.ConfigureServices(IServiceCollection services) in C:\Users\davidk\Desktop\WebApplication1\WebApplication1\Startup.cs:line 49
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at WebApplication1.Program.BuildWebHost(String[] args) in C:\Users\davidk\Desktop\WebApplication1\WebApplication1\Program.cs:line 21
>    at WebApplication1.Program.Main(String[] args) in C:\Users\davidk\Desktop\WebApplication1\WebApplication1\Program.cs:line 17

Any ideas it's happening when calling .AddUserManager<Justin.AspNetCore.LdapAuthentication.LdapUserManager<ApplicationUser>>()

**Comment by jusbuc2k** [comment]
@Dave3of5, this is the same as #2; I published version 2.0.0-preview00 (link bellow) yesterday morning targeting .NET Standard 2.0 / ASP.NET Identity 2.0 to resolve this issue. Can you see if this works for you, it resolved the same problem for the OP in that case. I'll remove the preview tag from the version if I know it's working for both of you.

https://www.nuget.org/packages/Justin.AspNetCore.LdapAuthentication/2.0.0-preview00

**Comment by Dave3of5** [comment]
HI that's great thank it now runs. Is there anyway to determine if the _signInManager is being created with the custom manager. When debug it won't authenticate correctly but I can't see why.

**Comment by Dave3of5** [comment]
OK I can see that the usermanager for my signinmanager is of the type:

Justin.AspNetCore.LdapAuthentication.LdapUserManager<ApplicationUser>

But PasswordSignInAsync still tries to access the Db rather than via Ldap.

Not quite sure why this would be the case, any ideas ?

**Comment by jusbuc2k** [comment]
@Dave3of5, that is odd. I just tested this on a File->New Project ASP.NET Core website and it works. Could you provide the contents of your ConfigureServices() method in the Startup class?

**Comment by Dave3of5** [comment]
It seems that the user needs to be registered within the system before it will authenticate using Ldap :-(

**Comment by Dave3of5** [comment]
I also see that it requires the "Normalised User Name" to be set to the dn of the AD user. Hopefully I'm almost there :-)

**Comment by Dave3of5** [comment]
Do you have an example of create a custom user store that implements it's own GetDistinguishedNameAsync ?

**Comment by jusbuc2k** [comment]
@Dave3of5,

I'll try to address some of your questions here and then close this issue since the original reported problem is fixed:

GetDistinguishedNameAsync() is a method on IUserLdapStore which is defined in this library. It's purpose is to allow you to change what DN is used in the bind call to the LDAP host which is used to validate the user's password. For most MS Active Directory scenarios, the default implementation I have provided will work, if the user types their UPN (userPrincipalName LDAP attribute) or plain username (sAMAccountName LDAP attribute). As you discovered, this assumes they are registered with ASP.NET Identity in the database first. 

To create a custom user store implementing IUserLdapStore, thus enabling you to override GetDistinguishedNameAsync(), you could create a new class that inherits from whatever the user store you are using (I'm assuming [the Entity Framework Core based one](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/UserStore.cs)?) and then implement the IUserLdapStore interface and then the GetDistinguishedNameAsync() method. Something like (but not exactly) this:

```csharp
public class MyCustomUserStore<TUser> : Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore<TUser>, Justin.AspNetCore.LdapAuthentication.IUserLdapStore<TUser> 
{
  // constructor goes here

  public Task<string> GetDistinguishedNameAsync(TUser user)
  {
  // return what should be used as the DN
  }

}
```

You would then register this user store in ConfigureServices() using services.AddIdentity()...

[Here is the documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers) on customizing ASP.NET Core Identity with custom stores. This is much more exhaustive than anything I can type out here. 

It should be pretty straightforward to implement an entire User Store that implements only the minimum required methods to get the user signed in and bypass the need to register the user in the database entirely, but I'm not sure if that is the scenario you are going for anyway. 

I hope this helps.
